// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfmxgfbgxsspmcsjkeic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmbXhnZmJneHNzcG1jc2prZWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzg0NDAsImV4cCI6MjA2ODkxNDQ0MH0.MoZ_ATdOg3XBppprsOJXp17AXHXhbRfzxXjjjFfJ71s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});